#+TITLE: Latent Dirichlet Allocation

#+BEGIN_QUOTE
  Documents are assumed to be composed of mixtures of topics, which are in turn composed of mixtures of words. If we knew the topic and document distributions, we could generate new documents using a probabilistic model. In LDA, we run this process in reverse to infer the topic and document distributions given the documents.
#+END_QUOTE
  
* TODO Leonhard Euler's Integral: A Historical Profile of the Gamma Function

* DOING LDA数学八卦

** $\Gamma$ 函数
   
$\Gamma$ 函数的定义：$$\Gamma(x)=\int_0^\infty{t^{x-1}e^{-t}dt}$$

该函数具有以下的递归性质：$$\Gamma(x+1)=x\Gamma(x)$$

其在实数集上的版本其实就是阶乘：$$\Gamma(n)=(n-1)!$$

因此 $\Gamma$ 函数的主要贡献在于将阶乘拓展到了实数域，也即使得 $(\frac{1}{2})!$ 的计算有意义。同时，由于可以使用 $\Gamma$ 函数计算实数的阶乘，因此现在也可以计算实数阶的导数或者积分，原因如下：

- 一阶导数： $nx^{n-1}$
- 二阶导数： $n(n-1)x^{n-2}$
- ...
- k阶导数： $n(n-1)(n-2)...(n-k+1)x^{n-k}=\frac{n!}{(n-k)!}x^{n-k}$

由于 $\Gamma$ 函数的存在，因此k阶导数可以表示为： $$\frac{\Gamma(n+1)}{\Gamma(n-k+1)}x^{n-k}$$

基于上式，取 $n=1,k=\frac{1}{2}$ ，可以计算 $x$ 的 $\frac{1}{2}$ 阶导数为： $$\frac{\Gamma(1+1)}{\Gamma(1-\frac{1}{2}+1)}x^{1-\frac{1}{2}}=\frac{2\sqrt{x}}{\sqrt{\pi}}$$

同时， $\Gamma$ 函数和欧拉常数 $\gamma$ 有密切联系：$$\gamma=-\frac{d\Gamma{(x)}}{dx}|_{x=1}=\lim_{n\rightarrow\infty}(1+\frac{1}{2}+\frac{1}{3}+\cdots+\frac{1}{n}-\log{n})$$

进一步还可以发现 $\Gamma$ 函数和黎曼函数 $\zeta(s)$ 有密切联系： $$\zeta(s)=1+\frac{1}{2^s}+\frac{1}{3^s}+\cdots$$

$\Gamma$ 函数是一个凸函数，且 $\log{\Gamma(x)}$ 也是一个凸函数，且可以证明：

-----
#+BEGIN_VERSE
*定理* : 如果 $f:(0,\infty)\rightarrow(0,\infty)$ ，且满足

1. $f(1)=1$
2. $f(x+1)=xf(x)$
3. $\log(fx)$ 是凸函数

那么 $f(x)$ 只能是 $\Gamma(x)$
#+END_VERSE
-----

** $\Psi$ 函数
   
如下函数被称为 Digamma 函数： $$\Psi(x)=\frac{d\log\Gamma(x)}{dx}$$

该函数有一个很漂亮的性质： $$\Psi(x+1)=\Psi(x)+\frac{1}{x}$$

函数 $\Psi(x)$ 和欧拉常数 $\gamma$ 以及 $\zeta$ 函数都有密切关系，令： $$\Psi_n(x)=\frac{d^{n+1}\log\Gamma(x)}{dx^{n+1}}$$

则 $\Psi_0(x)=\Psi(x)$ ，且：
$$\Psi(1)=-\gamma, \Psi(2)=1-\gamma$$
$$\Psi_1(1)=\zeta(2)=\frac{\pi^2}{6},\Psi_2(1)=-2\zeta(3)$$

** $\Gamma$ 分布

对 $\Gamma$ 函数做一个变形，可以得到： $$\int_0^\infty{\frac{x^{\alpha-1}e^{-x}}{\Gamma(\alpha)}}dx=1$$

将积分中的函数看作是概率密度，可以得到一个最简单形式的 $\Gamma$ 分布的密度函数： $$\Gamma(x|\alpha)=\frac{x^{\alpha-1}e^{-x}}{\Gamma(\alpha)}$$

做一个变换 $x={\beta}t$ ，就得到 $\Gamma$ 分布更一般的形式： $$\Gamma(t|\alpha,\beta)=\frac{\beta^{\alpha}t^{\alpha-1}e^{-\beta{t}}}{\Gamma(\alpha)}$$

其中 $\alpha$ 是 shape parameter，主要决定了分布曲线的形状，而 $\beta$ 称为 rate parameter 或者 inverse scale parameter，主要决定曲线有多陡。

指数分布和 $\chi^2$ 分布都是特殊的 $\Gamma$ 分布。
