* 经验风险与结构风险

** 一般误差与经验误差

-  一般误差：模型在任意样本下得到的误差，也就是模型的真实误差；
-  经验误差：训练样本的误差，由于是基于训练样本的，也就是基于已知经验的，称为经验误差。

机器学习的目标是最小化一般误差，但是由于是NP难题，因此一般转而最小化经验误差（ERM），但是这种方式并非是最好的（典型的比如过拟合），也就是说经验误差来代替一般误差不是最优的。

*** 马尔可夫不等式

马尔可夫不等式给出了随机变量的函数大于等于某正数的概率的上界，其数学表述为：\(P(X{\ge}a){\le}\frac{E(X)}{a}\)

*** 切比雪夫不等式

切比雪夫不等式是马尔可夫不等式的特殊情况，描述了这样一个事实，事件大多会集中在均值附近。其数学表述为：
\(P(|X-\mu|{\ge}k\sigma)\le\frac{1}{k^2}\)其中\(\mu\)是期望，\(\sigma\)是标准差。

文字解释为：

#+BEGIN_QUOTE
  任意一个数据集中，位于其平均数k个标准差范围内的比例（或部分）总是至少为\(1-1/k_2\)，其中k为大于1的任意正数。

  对于k=2，k=3和k=5有如下结果：

  -  所有数据中，至少有3/4（或75%）的数据位于平均数2个标准差范围内。
  -  所有数据中，至少有8/9（或88.9%）的数据位于平均数3个标准差范围内。
  -  所有数据中，至少有24/25（或96%)的数据位于平均数5个标准差范围内

  作者：马horse
  链接：https://www.zhihu.com/question/27821324/answer/92675490
  来源：知乎
  著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
#+END_QUOTE

** ERM(Empirical Risk Minimization)

-  经验误差存在上限，是其一般误差比较好的估计；
-  选择最小经验误差的拟合函数，其与一般误差函数的差异不超过2r。

** SRM(Structural Risk Minimization)

综合ERM与置信范围，寻求一个折中的最佳点。

** 参考

- [[https://blog.csdn.net/u013709270/article/details/53997686][经验风险与结构风险]]

* 损失函数与风险函数

损失函数度量模型一次预测的好坏，风险函数度量平均意义下模型预测的好坏。

损失函数是\(f(X)\)和Y的非负实值函数，记做L(Y,f(X))。损失函数是经验风险函数的核心部分，也是结构风险函数的重要组成部分，模型的风险结构包括了风险项和正则项：
\(\theta^*=argmin_{\theta}\frac{1}{N}\sum_{i=1}^{N}L(y_i,f(x_i;\theta))+\lambda \Phi(\theta)\)其中\(\Phi\)是正则化项或者惩罚项，可以是L1，也可以是L2或者其他正则函数。

常用的损失函数：

1. 0-1损失函数：\(L(Y,f(X))= \begin{cases}1,&\text{$Y{\ne}f(X)$}\\0,&\text{$Y=f(X)$}\end{cases}\)
2. 平方损失函数（quadratic loss function）：\(L(Y,f(X))=(Y-f(X))^2\)
3. 绝对损失函数：\(L(Y,f(X))=|Y-f(X)|\)
4. 对数损失函数：\(L(Y,P(Y|X))=-logP(Y|X)\)

* 参考

-  李航，《统计学习方法》
-  [[https://blog.csdn.net/u010976453/article/details/78488279][机器学习中的损失函数（着重比较：hinge loss vs softmax loss）]]
