--------------

* 文献

** TODO

[[[[http://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/icdm08b.pdf]]][Liu
F T, Kai M T, Zhou Z H. Isolation Forest{C}// Eighth IEEE International
Conference on Data Mining. IEEE, 2009:413-422.]]

*** Introduction

目前已有的大多数方式都是对正常行为进行画像，然后以此为基准检测不符合画像的样本为异常行为。这种方式有统计式的、分类式的和聚类式的，缺点是：

1. 通常这些anomaly
   detector都是针对正常行为优化的（因为正常行为的数据量远远大于异常行为）；
2. 受制于算法复杂度，只能针对低维数据和小数据量的数据。

利用了异常样本的两个特点，*few and different* ：

1. 样本少；
2. 特征相对于正常样本有显著的不同。

#+BEGIN_QUOTE
  In other words, anomalies are 'few and different', which make them
  more susceptible to isolation than normal points. Because of this,
  anomalies are isolated closer to the root of the tree; whereas normal
  points are isolated at the deeper end of the tree.
#+END_QUOTE

方法只需要两个参数：树的数量和子采样的数量。

*** Isolation and Isolation Trees

** [[[[https://www.researchgate.net/publication/224624985_Data_outlier_detection_using_the_Chebyshev_theorem]]][Amidan

B G, Ferryman T A, Cooley S K. Data outlier detection using the
Chebyshev theorem{C}// IEEE Aerospace Conference. IEEE,
2005:3814-3819.]]

分两步走，第一步确定哪些数据肯定不是异常，并使用这些肯定不是异常的数据来计算标准差、均值等。计算方式为$k=$，其中$p<sub>1</sub>$原文描述为异常点可能的比例稍大的值：

#+BEGIN_QUOTE
  The value of (p\_1) is used to determine which data are potential
  outliers. It should be larger than the overall probability of seeing
  an expected outlier. Values like 0.10, 0.05, or 0.01 are reasonable
  for (p\_1).
#+END_QUOTE

使用第一步计算出来的异常将数据剔除后再选取$p<sub>2</sub>$进行计算阈值得到异常点。

每一步，取阈值的方式为： [ODV\_{1U}=\mu+k\sigma] [ODV\_{1L}=\mu-k\sigma]
